markdown: CommonMarkGhPages
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Welcome to Spencer Runde's ePortfolio!
description: This ePortfolio will be used to host my CS Capstone project.

theme: jekyll-theme-slate